# This is the top-level variable file that will be used for the FlexPod setup. It is setup in this case to have Fibre Channel SAN boot with
# FC-NVMe and NFS storage protocols. Notice that the configure_iscsi variable is commented out, meaning iSCSI boot will not be configured.
# iSCSI variable parameters are left in for guidance and commented out where necessary. If iSCSI boot is configured, uncomment all iSCSI variables.
#
# Commenting out the following two variables will skip the iSCSI and/or FC storage configurations
#configure_iscsi: "yes"
configure_fc: "yes"
# FC-NVMe Configuration, only define this if configure_fc is defined
configure_fc_nvme: "yes"
#
# Commenting out the configure_nfs will skip the NFS related configuration including
# datastore mounting and NFS VMK definition.
#
configure_nfs: "yes"
#
# Update the the following lines to setup NTP Server(s)
# Note that we are setting up NTP Distribution on the Nexus switches and these are the two Nexus mgmt0 IP addresses that will be used for the other FlexPod equipment.
ntp_servers:
  - ip_address: "192.168.156.135"
  - ip_address: "192.168.156.136"
ib_mgmt_ntp_servers:                # InBand Management NTP Addresses to be used by ESXi hosts and VMs
  - ip_address: "10.1.156.135"
  - ip_address: "10.1.156.136"

# Update the the following lines to setup DNS Server(s)
dns_servers:
  - ip_address: "10.1.156.250"
  - ip_address: "10.1.156.251"

# DNS Domain Name
dns_domain_name: "flexpod.cisco.com"

# Update the the following line to setup Timezone
time_zone: 'America/New_York'

# This is the list of all the VLANs that will be defined on Nexus, Storage, UCS, and VMware
# VLAN Names are adjustable and can be modified in here
#
native_vlan_name: 'Native-Vlan' # Native VLAN
oob_vlan_name: 'OOB-MGMT' # Out of Band Mgmt VLAN
ib_vlan_name: 'IB-MGMT' # IN BAND Management VLAN
vm_vlan_name: 'VM-Traffic' # VLAN to carry VM traffic on VDS
vmotion_vlan_name: 'vMotion' # vMotion VLAN
nfs_vlan_name: 'Infra-NFS' # NFS Traffic between ESXi and Storage
iscsiA_vlan_name: 'Infra-iSCSI-A' # iSCSI-A VLAN (if needed)
iscsiB_vlan_name: 'Infra-iSCSI-B' # iSCSI-B VLAN (if needed)
#
# lan_state should be set to 'present' to configure the objects
# In future, this parameter will be used for deleting the configuration
#
lan_state : 'present'
#
# VLAN Lists - Comment out or remove any VLANs not being used.
#
# The ib_mgmt_vlan_list contains one entry, the IB-MGMT VLAN.
#
ib_mgmt_vlan_list:
  - name: "{{ ib_vlan_name }}"
    id: '113'
    native: 'no'
    state: "{{lan_state}}"
#
# The storage_vlan_list contains VLANs that are configured on the storage controllers.
# These VLANs are also configured in the UCS and in the Nexus switches. This list has
# two extra fields, storage_protocol, and fabric. Do not remove these extra fields.
#
storage_vlan_list:
  - name: "{{ nfs_vlan_name }}"
    id: '3050'
    native: 'no'
    storage_protocol: NFS
    state: "{{lan_state}}"
    # ISCSI A and B VLANs should be deleted or commended out for Fiber-Channel-Only deployments
#  - name: "{{ iscsiA_vlan_name }}"
#    id: '3010'
#    native: 'no'
#    storage_protocol: iSCSI
#    fabric: A
#    state: "{{lan_state}}"
#  - name: "{{ iscsiB_vlan_name }}"
#    id: '3020'
#    native: 'no'
#    storage_protocol: iSCSI
#    fabric: B
#    state: "{{lan_state}}"
#
# The remaining_vlan_list contains all vlans that are not configured on storage,
# but are configured in Nexus and UCS.
#
remaining_vlan_list:
  - name: "{{ native_vlan_name }}"
    id: '2'
    native: 'yes'
    state: "{{lan_state}}"
  - name: "{{ oob_vlan_name }}"
    id: '13'
    native: 'no'
    state: "{{lan_state}}"
  - name: "{{ vm_vlan_name }}"
    id: '900'
    native: 'no'
    state: "{{lan_state}}"
  - name: "{{ vmotion_vlan_name }}"
    id: '3000'
    native: 'no'
    state: "{{lan_state}}"

# VLANs definitions below will be used to setup trunk ports on Nexus Switches
# all_vlans_list: for vpc_peer_link and UCS FI trunk ports
# These VLANs must be same or a subset of the vlan_list above
# In future, these values will be auto-generated
#
all_vlans_list: "13,113,900,3000,3050"
# storage_vlans_list: for vpc_peer_link and UCS FI trunk ports
storage_vlans_list: "113,3050"
# mgmt_vlans_list: for uplink/management switch trunk port
mgmt_vlans_list: "13,113"
#
native_vlan_id: "2"
#
vmotion_portgroup: "VMKernel-vMotion"
#
vds_vlan_list:
  - name: "{{ vm_vlan_name }}"
    # portgroup name will be configured in VMware
    portgroup_name: "{{ vm_vlan_name }}"
    id: '900'
    active_uplinks: 
      - "Uplink 1"
      - "Uplink 2"
    standby_uplinks: []
  - name: "{{ vmotion_vlan_name }}"
    # portgroup name will be configured in VMware
    portgroup_name: "{{ vmotion_portgroup }}"
    id: '3000'
    active_uplinks: "Uplink 2"
    standby_uplinks: "Uplink 1"
#
nfs_portgroup: "VMKernel-Infra-NFS"
esxi_nfs_vlan: "3050"
#
oob_mgmt_portgroup: "OOB-MGMT Network"
oob_mgmt_vlan: "13"
#
#VSAN Parameters
#
vsan_list:
  - name: 'FlexPod-Fabric-A'
    vsan_id: '101'
    fcoe_vlan: '101'
    fabric: 'A'
  - name: 'FlexPod-Fabric-B'
    vsan_id: '102'
    fcoe_vlan: '102'
    fabric: 'B'
#
# Storage FC WWPNs (capture from storage system)
#
fcp_lif_01a: '20:01:d0:39:ea:17:12:9b'
fcp_lif_02a: '20:03:d0:39:ea:17:12:9b'
fcp_lif_01b: '20:02:d0:39:ea:17:12:9b'
fcp_lif_02b: '20:04:d0:39:ea:17:12:9b'
#
# Storage FC-NVMe WWPNs (capture from storage system)
#
fc_nvme_lif_01a: '20:06:d0:39:ea:17:12:9b'
fc_nvme_lif_02a: '20:08:d0:39:ea:17:12:9b'
fc_nvme_lif_01b: '20:07:d0:39:ea:17:12:9b'
fc_nvme_lif_02b: '20:09:d0:39:ea:17:12:9b'
#
# UCS FC WWPNs (capture from the UCS Service Profiles)
#
ucs_host_01_a: '20:00:00:25:b5:a1:6a:01'
ucs_host_01_b: '20:00:00:25:b5:a1:6b:01'
#
ucs_host_02_a: '20:00:00:25:b5:a1:6a:03'
ucs_host_02_b: '20:00:00:25:b5:a1:6b:03'
#
ucs_host_03_a: '20:00:00:25:b5:a1:6a:05'
ucs_host_03_b: '20:00:00:25:b5:a1:6b:05'
#
# UCS FC-NVMe WWPNs (capture from the UCS Service Profiles)
#
ucs_nvme_01_a: '20:00:00:25:b5:a1:6a:00'
ucs_nvme_01_b: '20:00:00:25:b5:a1:6b:00'
#
ucs_nvme_02_a: '20:00:00:25:b5:a1:6a:02'
ucs_nvme_02_b: '20:00:00:25:b5:a1:6b:02'
#
ucs_nvme_03_a: '20:00:00:25:b5:a1:6a:04'
ucs_nvme_03_b: '20:00:00:25:b5:a1:6b:04'
#
# Storage iSCSI Target Interfaces
#
iscsi_lif_01a: '192.168.10.141'
iscsi_lif_01b: '192.168.20.141'
iscsi_lif_02a: '192.168.10.142'
iscsi_lif_02b: '192.168.20.142'
#
# Storage iSCSI Target IQN
#
storage_iscsi_IQN: 'iqn.1992-08.com.netapp:sn.51dff97a069611ec96ecd039ea166b8c:vs.3'
#
# Storage NFS Infrastructure LIF Interfaces
#
nfs_lif_01: '192.168.50.141'
nfs_lif_02: '192.168.50.142'
#
# VMware Configurations
# provide the user names and passwords to connect to the ESXi ntp_servers
# and VMware vCenter
#
esxi_username: root
esxi_password: "{{ ansible_ssh_pass }}"
#
vcenter_dc: FlexPod-DC
vcenter_cluster: FlexPod-Management
#
vcenter_hostname: "10.1.156.100"
# e.g. vcenter_hostname: 10.50.160.100
vcenter_username: "administrator@vsphere.local"
# e.g. vcenter_username: administrator@vsphere.local
vcenter_password: <password>
# e.g. vcenter_password: "cisco!23"
#
# DVS Parameters; use version 7.0.2 for VMware 7.0U2 or above
#
dvs_name: "vDS0"
dv_version: "7.0.2"
dv_uplink: "2"
dv_protocol: "lldp"
dv_operation: "both"
