---
    # VMware Adapter Policy for High Traffic
    # The call break down should not be needed but adding all the
    # parameters to single ucs_managed_object was causing error


      - name: Create VMware Ethernet Adapter Policy for High Traffic
        cisco.ucs.ucs_managed_objects:
          hostname: "{{ inventory_hostname }}"
          username: "{{ username }}"
          password: "{{ password }}"
          objects:
          - {
              "module": "ucsmsdk.mometa.adaptor.AdaptorHostEthIfProfile",
              "class": "AdaptorHostEthIfProfile",
              "properties": {
                  "parent_mo_or_dn": "org-root",
                  "name": "{{adapter_policy_name}}"
              },
              "children": [
                {
                  "module": "ucsmsdk.mometa.adaptor.AdaptorEthCompQueueProfile",
                  "class": "AdaptorEthCompQueueProfile",
                  "properties": {
                    "count": "9"
                  }
                },
                {
                  "module": "ucsmsdk.mometa.adaptor.AdaptorEthInterruptProfile",
                  "class": "AdaptorEthInterruptProfile",
                  "properties": {
                    "count": "11"
                  }
                },
                {
                  "module": "ucsmsdk.mometa.adaptor.AdaptorRssProfile",
                  "class": "AdaptorRssProfile",
                  "properties": {
                    "receive_side_scaling": "enabled"
                  }
                }
              ]
            }

      - name: Update VMware Ethernet Adapter Policy for High Traffic
        cisco.ucs.ucs_managed_objects:
          hostname: "{{ inventory_hostname }}"
          username: "{{ username }}"
          password: "{{ password }}"
          objects:
          - {
              "module": "ucsmsdk.mometa.adaptor.AdaptorHostEthIfProfile",
              "class": "AdaptorHostEthIfProfile",
              "properties": {
                  "parent_mo_or_dn": "org-root",
                  "name": "{{adapter_policy_name}}"
              },
              "children": [
                {
                  "module": "ucsmsdk.mometa.adaptor.AdaptorEthWorkQueueProfile",
                  "class": "AdaptorEthWorkQueueProfile",
                  "properties": {
                    "count": "1"
                  }
                },
                {
                  "module": "ucsmsdk.mometa.adaptor.AdaptorEthRecvQueueProfile",
                  "class": "AdaptorEthRecvQueueProfile",
                  "properties": {
                    "count": "8"
                  }
                }
              ]
            }
