---
# IP Address Pool for Management (KVM Access etc.)
#Configure Management IP pool on UCS
- name: Configure ext-mgmt IPv4 address pools
  cisco.ucs.ucs_ip_pool:
    hostname: "{{ inventory_hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    name: "{{ mgmt_pool_name}}"
    order: "{{ lan_assign_order}}"
    first_addr: "{{mgmt_first_ip}}"
    last_addr: "{{ mgmt_last_ip}}"
    subnet_mask: "{{ mgmt_subnet_mask}}"
    default_gw: "{{ mgmt_default_gw }}"
