---
# Configuration of VLANs in UCSM

- name: Configure UCS VLANs
  cisco.ucs.ucs_vlans:
    hostname: "{{ inventory_hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    name: "{{ item.name }}"
    id: "{{ item.id }}"
    native: "{{ item.native }}"
    state: "{{ item.state }}"
  with_list: "{{ vlan_list }}"
