---
# This task sets up the VSAN configuration for both MDS switches
# specific variables from the MDS-A/B variables files
#
  - name: MDS VSAN - Create VSAN and Add port-channel
    cisco.nxos.nxos_vsan:
      vsan:
        - id: "{{ vsan_id }}"
          name: "{{ vsan_name}}"
          interface:
            - san-port-channel {{ port_channel_id }}
          remove: False
#
  - name: MDS VSAN - Add storage ports
    cisco.nxos.nxos_vsan:
      vsan:
        - id: "{{ vsan_id }}"
#          name: "{{ vsan_name}}"
          interface:
            - "{{ item.interface }}"
          remove: False
    with_list: "{{ storage_interface_list }}"
#
  - name: MDS VSAN - Configure Smart Zoning
    cisco.nxos.nxos_config:
      lines:
        - zone smart-zoning enable vsan {{ vsan_id }}
