---
  - name: vCenter vDS Portgroup Creation
    community.vmware.vmware_dvs_portgroup:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      switch_name: '{{ dvs_name }}'
      portgroup_name: '{{ item.portgroup_name }}'
      vlan_id: '{{ item.id }}'
      portgroup_type: earlyBinding
      num_ports: 120
      state: present
      teaming_policy:
        active_uplinks: "{{ item.active_uplinks }}"
        standby_uplinks: "{{ item.standby_uplinks }}"
    with_list: "{{ vds_vlan_list }}"
