---
# Variables defined here are specific to MDS-A
#
#  Variables used to create port channel to UCS.
  port_channel_id: 15
  port_channel_speed: "32000"
  port_channel_description: "AA16-6454-A"
#
#  VSAN number to use used for a the fabric being created
  vsan_id: "{{ vsan_list[0].vsan_id }}"
  vsan_name: "{{ vsan_list[0].name }}"
#
# The zone names and zoneset name used in the configuration
  zoneset_name: FlexPod-Fabric-A
  fcp_zone_name: "FCP-{{ svm_specs.svm_name }}-A"
  fc_nvme_zone_name: "FC-NVMe-{{ svm_specs.svm_name }}-A"
#
# Device alias lists using device names and PWWNs from CVD.  Update the PWWNs to match your deployment
  fcp_device_alias_list:
    - device_name: "{{ svm_specs.svm_name }}-fcp-lif-01a"
      pwwn: "{{ fcp_lif_01a }}"
      dev_type: target
    - device_name: "{{ svm_specs.svm_name }}-fcp-lif-02a"
      pwwn: "{{ fcp_lif_02a }}"
      dev_type: target
    - device_name: "VM-Host-Infra-FCP-01-A"
      pwwn: "{{ ucs_host_01_a }}"
      dev_type: initiator
    - device_name: "VM-Host-Infra-FCP-02-A"
      pwwn: "{{ ucs_host_02_a }}"
      dev_type: initiator
    - device_name: "VM-Host-Infra-FCP-03-A"
      pwwn: "{{ ucs_host_03_a }}"
      dev_type: initiator
#
  fc_nvme_device_alias_list:
    - device_name: "{{ svm_specs.svm_name }}-fc-nvme-lif-01a"
      pwwn: "{{ fc_nvme_lif_01a }}"
      dev_type: target
    - device_name: "{{ svm_specs.svm_name }}-fc-nvme-lif-02a"
      pwwn: "{{ fc_nvme_lif_02a }}"
      dev_type: target
    - device_name: "VM-Host-Infra-FC-NVMe-01-A"
      pwwn: "{{ ucs_nvme_01_a }}"
      dev_type: initiator
    - device_name: "VM-Host-Infra-FC-NVMe-02-A"
      pwwn: "{{ ucs_nvme_02_a }}"
      dev_type: initiator
    - device_name: "VM-Host-Infra-FC-NVMe-03-A"
      pwwn: "{{ ucs_nvme_03_a }}"
      dev_type: initiator
#
# MDS Switch FC Interface List
#
  storage_interface_list:
    - interface: "fc1/1"
      description: "AA16-A400-01:5a"
      speed: "32000"
    - interface: "fc1/2"
      description: "AA16-A400-02:5a"
      speed: "32000"
#
  ucs_interface_list:
    - interface: "fc1/5"
      description: "AA16-6454-A:fc1/1"
      speed: "32000"
    - interface: "fc1/6"
      description: "AA16-6454-A:fc1/2"
      speed: "32000"
