---
  - name: Configure ESXi NTP server
    community.vmware.vmware_host_ntp:
      hostname: '{{ inventory_hostname }}'
      username: '{{ ansible_user }}'
      password: '{{ ansible_ssh_pass }}'
      validate_certs: no
      esxi_hostname: '{{ inventory_hostname }}'
      ntp_servers: '{{ ntp_servers_list }}'
    delegate_to: localhost

  - name: Start ESXi ntpd for the hosts
    community.vmware.vmware_host_service_manager:
      hostname: '{{ inventory_hostname }}'
      username: '{{ ansible_user }}'
      password: '{{ ansible_ssh_pass }}'
      validate_certs: no
      esxi_hostname: '{{ inventory_hostname }}'
      service_name: ntpd
      service_policy: on
    delegate_to: localhost
