---
#
# All the NFS datastores defined in ESXihosts/defaults/main.yml
# are added to all the ESXi hosts. configure_nfs variable must be present
# for the NFS datastore mount
#
  - name: Add NFS datastore to each host
    community.vmware.vmware_host_datastore:
      hostname: '{{ inventory_hostname }}'
      username: '{{ ansible_user }}'
      password: '{{ ansible_ssh_pass }}'
      esxi_hostname: '{{ inventory_hostname }}'
      datastore_name: '{{ item.mount }}'
      datastore_type: '{{ nfs_datastore_type }}'
      nfs_server: '{{ item.server }}'
      nfs_path: '/{{item.mount}}'
      validate_certs: no
      state: present
    delegate_to: localhost
    with_list: '{{ nfs_datastore_list }}'
    when: configure_nfs is defined
